### ISSUE TITLE
Const property in a blueprint causing error

### ISSUE THREAD

**Issue by mwojt-platige** [Mystfit/Unreal-StableDiffusionTools#10]
Hello,

I think you've wrapped this private variable in a const method and decorated it as a read-only `UPROPERTY`, but it should be a `UFUNCTION` instead.

```
StableDiffusionTools/Source/StableDiffusionSequencer/Public/StableDiffusionPromptMovieSceneSection.h(22): Error: Const properties are not supported.
```

**Comment by Mystfit** [comment]
Oops, I think that was supposed to be a UFUNCTION. Thanks!

**Comment by Mystfit** [comment]
Closed in https://github.com/Mystfit/Unreal-StableDiffusionTools/commit/158bc13a8a91ebb0cb8c7645bca9453843609e59
