### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by ltsfwrs** [Mystfit/Unreal-StableDiffusionTools#12]
Console errors:
```
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error: NameError: name 'SD_dependencies_installed' is not defined
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error:   File "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\huggingface_hub\__init__.py", line 254, in __getattr__
LogPython: Error:     raise AttributeError(f"No {package_name} attribute {name}")
LogPython: Error: AttributeError: No huggingface_hub attribute utils

LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "E:/Unreal Projects/Test/Plugins/StableDiffusionTools/Content/Python/init_unreal.py", line 27, in <module>
LogPython: Error:     import load_diffusers_bridge
LogPython: Error:   File "E:\Unreal Projects/Test/Plugins/StableDiffusionTools/Content/Python\load_diffusers_bridge.py", line 2, in <module>
LogPython: Error:     import DiffusersBridge
LogPython: Error:   File "E:\Unreal Projects/Test/Plugins/StableDiffusionTools/Content/Python\DiffusersBridge.py", line 4, in <module>
LogPython: Error:     import torch
LogPython: Error:   File "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\torch\__init__.py", line 139, in <module>
LogPython: Error:     raise err
LogPython: Error: OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
```

**Comment by Mystfit** [comment]
It looks as though the assets haven't installed properly. Can you close the plugin window, restart Unreal, reopen the plugin window and try to reinstall the dependencies then restart Unreal again?

**Comment by Mystfit** [comment]
Ok, I just ran into the error from the first part. At the moment the UI will throw that error when the plugin is visible when opening Unreal. Closing the plugin window and reopening it should fix that issue.

**Comment by ltsfwrs** [comment]
Now it just says "collecting torch" while my computer freezes

**Comment by Mystfit** [comment]
What happens if you leave it for around 15 minutes?

**Comment by Mystfit** [comment]
@ltsfwrs Did you manage to install torch int he end?

**Comment by ltsfwrs** [comment]
No, it just keeps getting stuck after a certain point.

```
LogFeaturePack: Error: Error in Feature pack E:/Unreal/UE_5.0/FeaturePacks/TP_VirtualRealityBP.upack. Failed to parse manifest: Invalid Json Token. Line: 43 Ch: 4
LogBlueprint: Warning: [AssetLog] E:\Unreal Projects\SuperAd\Plugins\StableDiffusionTools\Content\UI\Widgets\BP_StableDiffusionViewportWidget.uasset: [Compiler] Input pin  Input Options Upscale  specifying non-default value no longer exists on node  Generate Image . Please refresh node or reset pin to default value to remove pin.
LogSlate: Took 0.000316 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Regular.ttf' (155K)
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error: NameError: name 'SD_dependencies_installed' is not defined
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error:   File "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\huggingface_hub\__init__.py", line 254, in __getattr__
LogPython: Error:     raise AttributeError(f"No {package_name} attribute {name}")
LogPython: Error: AttributeError: No huggingface_hub attribute utils
LogSlate: Took 0.000495 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/DroidSansMono.ttf' (77K)
LogSlate: Took 0.000584 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Italic.ttf' (157K)
LogViewport: Scene viewport resized to 2038x874, mode Windowed.
LogStall: Startup...
LogStall: Startup complete.
LogLoad: (Engine Initialization) Total time: 17.86 seconds
LogLoad: (Engine Initialization) Total Blueprint compile time: 0.00 seconds
LogAssetRegistry: Asset discovery search completed in 12.7778 seconds
LogCollectionManager: Fixed up redirectors for 0 collections in 0.000002 seconds (updated 0 objects)
LogContentStreaming: Texture pool size now 1000 MB
LogSlate: Took 0.000361 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Bold.ttf' (160K)
LogPython: Stable Diffusion dependencies are available
LogPython: Skipping default Diffusers Bridge load until dependencies have been installed
LogNiagara: Compiling System NiagaraSystem /Game/Snow_FX/Niagara_particles/Fall_Snow_Emitter_System.Fall_Snow_Emitter_System took 2.896061 sec, no shader worker used.
LogNiagara: Compiling System NiagaraSystem /Game/Snow_FX/Niagara_particles/Trail_Snow_System.Trail_Snow_System took 2.797077 sec, no shader worker used.
LogConcert: Display: Server 6AFBBC8F4C8F536660337F8D1B4F6274 discovered.
LogConcert: [Pending] Creating Session '6AFBBC8F4C8F536660337F8D1B4F6274_1_2022.11.04-05.44.01_SuperAd'...
LogConcert: [Pending] Creating Session '6AFBBC8F4C8F536660337F8D1B4F6274_1_2022.11.04-05.44.01_SuperAd'... - Attempting Remote Connection...
LogConcert: Display: Initialized Concert session '6AFBBC8F4C8F536660337F8D1B4F6274_1_2022.11.04-05.44.01_SuperAd' (Id: 23E802F6449E67936922A9B306252384, Owner: Grafik).
LogConcert: Display: Connecting to Concert session '6AFBBC8F4C8F536660337F8D1B4F6274_1_2022.11.04-05.44.01_SuperAd' (Id: 23E802F6449E67936922A9B306252384, Owner: Grafik).
LogConcert: Display: Connected to Concert session '6AFBBC8F4C8F536660337F8D1B4F6274_1_2022.11.04-05.44.01_SuperAd' (Id: 23E802F6449E67936922A9B306252384, Owner: Grafik).
LogConcert: [Success] Created Session '6AFBBC8F4C8F536660337F8D1B4F6274_1_2022.11.04-05.44.01_SuperAd'
LogSlate: Window 'Stable Diffusion Tools' being destroyed
LogSlate: Window 'Stable Diffusion Tools' being destroyed
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error:   File "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\huggingface_hub\__init__.py", line 254, in __getattr__
LogPython: Error:     raise AttributeError(f"No {package_name} attribute {name}")
LogPython: Error: AttributeError: No huggingface_hub attribute utils
LogPython: Installing dependency torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
LogDerivedDataCache: C:/Users/Grafik/AppData/Local/UnrealEngine/Common/DerivedDataCache: Maintenance finished in +00:00:14.261 and deleted 0 file(s) with total size 0 MiB.
LogPython: Installing dependency diffusers
LogPython: Installing dependency transformers
LogPython: Installing dependency scipy
LogPython: Installing dependency ftfy
LogPython: Installing dependency realesrgan
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "E:/Unreal Projects/SuperAd/Plugins/StableDiffusionTools/Content/Python/load_diffusers_bridge.py", line 2, in <module>
LogPython: Error:     import DiffusersBridge
LogPython: Error:   File "E:\Unreal Projects/SuperAd/Plugins/StableDiffusionTools/Content/Python\DiffusersBridge.py", line 5, in <module>
LogPython: Error:     from torch import autocast
LogPython: Error: ImportError: cannot import name 'autocast' from 'torch' (unknown location)
```

**Comment by Mystfit** [comment]
Can you try installing the latest version of the plugin? It will get rid of
the first batch of errors and try and update your torch to the latest
version.

**Comment by ltsfwrs** [comment]
`LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "E:/Unreal Projects/SuperAd/Plugins/StableDiffusionTools/Content/Python/load_diffusers_bridge.py", line 2, in <module>
LogPython: Error:     import DiffusersBridge
LogPython: Error:   File "E:\Unreal Projects/SuperAd/Plugins/StableDiffusionTools/Content/Python\DiffusersBridge.py", line 7, in <module>
LogPython: Error:     from diffusers import StableDiffusionImg2ImgPipeline, StableDiffusionPipeline
LogPython: Error:   File "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\diffusers\__init__.py", line 20, in <module>
LogPython: Error:     from .modeling_utils import ModelMixin
LogPython: Error:   File "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\diffusers\modeling_utils.py", line 29, in <module>
LogPython: Error:     from .utils import (
LogPython: Error: ImportError: cannot import name 'is_torch_version' from 'diffusers.utils' (E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\diffusers\utils\__init__.py)`

**Comment by Mystfit** [comment]
Just to verify, are you using an NVIDIA graphics card with CUDA support?

**Comment by ltsfwrs** [comment]
Yes an RTX 2080

**Comment by gschian0** [comment]
> `LogPython: Error: Traceback (most recent call last): LogPython: Error: File "E:/Unreal Projects/SuperAd/Plugins/StableDiffusionTools/Content/Python/load_diffusers_bridge.py", line 2, in <module> LogPython: Error: import DiffusersBridge LogPython: Error: File "E:\Unreal Projects/SuperAd/Plugins/StableDiffusionTools/Content/Python\DiffusersBridge.py", line 7, in <module> LogPython: Error: from diffusers import StableDiffusionImg2ImgPipeline, StableDiffusionPipeline LogPython: Error: File "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\diffusers\__init__.py", line 20, in <module> LogPython: Error: from .modeling_utils import ModelMixin LogPython: Error: File "E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\diffusers\modeling_utils.py", line 29, in <module> LogPython: Error: from .utils import ( LogPython: Error: ImportError: cannot import name 'is_torch_version' from 'diffusers.utils' (E:\Unreal\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\diffusers\utils\__init__.py)`

I am getting a similar error 
`Looking for module git
Log          LogPython                 Looking for module torch
Log          LogPython                 Looking for module torchvision
Log          LogPython                 Looking for module torchaudio
Log          LogPython                 Looking for module diffusers
Log          LogPython                 Looking for module transformers
Log          LogPython                 Looking for module scipy
Log          LogPython                 Looking for module ftfy
Log          LogPython                 Looking for module realesrgan
Log          LogPython                 Looking for module accelerate
Log          LogPython                 Looking for module xformers
Log          LogPython                 Stable Diffusion dependencies are available
Error        LogPython                 Traceback (most recent call last):
Error        LogPython                   File "S:/UnrealEngine/Stable_Diffusion_UE5/Plugins/StableDiffusionTools/Content/Python/init_unreal.py", line 35, in <module>
Error        LogPython                     import load_diffusers_bridge
Error        LogPython                   File "S:\UnrealEngine/Stable_Diffusion_UE5/Plugins/StableDiffusionTools/Content/Python\load_diffusers_bridge.py", line 2, in <module>
Error        LogPython                     import DiffusersBridge
Error        LogPython                   File "S:\UnrealEngine/Stable_Diffusion_UE5/Plugins/StableDiffusionTools/Content/Python\DiffusersBridge.py", line 4, in <module>
Error        LogPython                     import torch
Error        LogPython                   File "C:\Program Files\Epic Games\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\torch\__init__.py", line 139, in <module>
Error        LogPython                     raise err
Error        LogPython                 OSError: [WinError 126] The specified module could not be found. Error loading "C:\Program Files\Epic Games\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.`

**Comment by gschian0** [comment]
I have a 3070 laptop gpu

**Comment by gschian0** [comment]
I get this error as well `LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "<string>", line 1, in <module>
LogPython: Error:   File "C:\Program Files\Epic Games\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\huggingface_hub\__init__.py", line 254, in __getattr__
LogPython: Error:     raise AttributeError(f"No {package_name} attribute {name}")
LogPython: Error: AttributeError: No huggingface_hub attribute utils`

**Comment by Mystfit** [comment]
> I get this error as well `LogPython: Error: Traceback (most recent call last): LogPython: Error: File "<string>", line 1, in <module> LogPython: Error: File "C:\Program Files\Epic Games\UE_5.0\Engine\Binaries\ThirdParty\Python3\Win64\lib\site-packages\huggingface_hub\__init__.py", line 254, in __getattr__ LogPython: Error: raise AttributeError(f"No {package_name} attribute {name}") LogPython: Error: AttributeError: No huggingface_hub attribute utils`

I'm going to try and finally fix this error tomorrow. It should go away if you reload the plugin window but I think the earlier error about torch not finding `caffe2_nvrtc.dll` is the culprit here which then causes the other libraries to not get loaded later on like the huggingface_hub module. Since torch is the culprit here I will have to examine what that dll actually links against to try and figure out if you are missing some sort of dependency. I'm hoping that the upstream torch hasn't gone and uploaded a broken package. I'm thinking about adding a button to recursively remove all installed packages so we can force a full dependency reinstallation and see if that solves the problem.

**Comment by Mystfit** [comment]
@gschian0 Just checking in on this issue. If you pull one of the latest plugin versions does it fix the caffe.dll error?

**Comment by Mystfit** [comment]
Closing this issue as the dependency installer process has been updated since this issue.
