### ISSUE TITLE
How to Update?

### ISSUE THREAD

**Issue by Tobe2d** [Mystfit/Unreal-StableDiffusionTools#15]
Whenever I update I lose the dependances and I have to download again ;-(

Is there away to pull the changes directly to the plugin folder? What is the best way to update from v0.3.5 to v0.4.0?

**Comment by Mystfit** [comment]
Which dependencies, the python ones listed in `install_dependencies.py` or the models?

I recommend replacing the `StableDiffusionTools` folder with the latest one from either the releases page or the top-most directory in this repository then click `Update dependencies` in the plugin window. Closing and re-opening the plugin is also another good way to make sure that the UI has picked up which dependencies are installed and if there are any missing. The plugin should always work as long as all of the dependencies listed list in the `install_dependencies.py` script are present. If any are missing, then the model section in the UI will be inactive. If all the dependencies are installed and up to date, then updating the dependencies should finish pretty quickly as nothing should get downloaded.

The python dependencies are located in `ENGINE_DIR\Binaries\ThirdParty\Python3\Win64\Lib\site-packages` should only get replaced if there is a newer version available. Models are downloaded to `USER_DIR\.cache\huggingface\diffusers` and are probably only updated when the source model card is updated.

**Comment by Tobe2d** [comment]
Thanks so much for the clearification. Aaaaaaaaand thank you so mych for the great plugin!
