### ISSUE TITLE
No module named 'numpy'

### ISSUE THREAD

**Issue by Tobe2d** [Mystfit/Unreal-StableDiffusionTools#19]
I had it working through v0.4.2. When Ireplaced the folder "StableDiffusionTools" in plugins with latest release v0.5.0 - Generator backends (hotfix1) I cant get it to work. I see the plugin in plugins page and it is activated, however, I am not seeing it in windows to start the UI. and in the log I get this:

`LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "G:/EpicGames/Unreal_Engine/Unreal Projects/StableDiffusionTools/Plugins/StableDiffusionTools/Content/Python/init_unreal.py", line 50, in <module>
LogPython: Error:     dynamic_import_from_src(os.path.join(pathlib.Path(__file__).parent.resolve(), "bridges"))
LogPython: Error:   File "G:/EpicGames/Unreal_Engine/Unreal Projects/StableDiffusionTools/Plugins/StableDiffusionTools/Content/Python/init_unreal.py", line 29, in dynamic_import_from_src
LogPython: Error:     imported_module = dynamic_import(module_name, py_file)
LogPython: Error:   File "G:/EpicGames/Unreal_Engine/Unreal Projects/StableDiffusionTools/Plugins/StableDiffusionTools/Content/Python/init_unreal.py", line 21, in dynamic_import
LogPython: Error:     module_spec.loader.exec_module(module)
LogPython: Error:   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
LogPython: Error:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
LogPython: Error:   File "G:\EpicGames\Unreal_Engine\Unreal Projects\StableDiffusionTools\Plugins\StableDiffusionTools\Content\Python\bridges\DiffusersBridge.py", line 3, in <module>
LogPython: Error:     import numpy as np
LogPython: Error: ModuleNotFoundError: No module named 'numpy'`

**Comment by Mystfit** [comment]
Go Windows->Stable Diffusion Dependencies Installer and update all your
dependencies and let me know if that resolves it.

**Comment by Tobe2d** [comment]
The error is gone after upding all dependencies.

Now the UI showing no model loaded and Generation is grayedout to me.

![image](https://user-images.githubusercontent.com/4099839/203985731-825fafe2-d44b-494b-8bf3-35daf8e99fba.png)


Lastly, I could not find where to check my huggingface token.

**Comment by Mystfit** [comment]
You need to click initialize the model first and then you can generate an
image. The token entry has been moved into `Project Settings->Stable
Diffusion Tools`. Pick a generator (Diffusers Bridge is local and will take
your hugging face token) and put the token into the bridge tokens map.

**Comment by Tobe2d** [comment]
Great! I got it up and running now. thank you so much ;-)

Side note.
Now I start migrating into 5.1 and following your instructions it is working nicly. however, when I dock StableDiffusionTools to the UI and start UE it does not load correctly. I have to close it and reopen it from the windoow --> StableDiffusionTools and it open without remembering where it was in the UI.
maybe it need some kind of delay when it load when UE start?

Just thought to point it out ;-)

**Comment by Mystfit** [comment]
The UI does now wait until python has finished loading all the initial python code that the widget likes to talk to but it seems to have broken again. Will look into that in a separate issue.
