### ISSUE TITLE
Animation pipeline: When will we be saved?

### ISSUE THREAD

**Issue by mischaschaub** [Mystfit/Unreal-StableDiffusionTools#2]
Just found the time to play for some hours with your plug-in. You made a great achievement, indeed. The difference between the silly UE4 models and the touch of the photos offers immense creative potential. So I beg you on my knees for a quick release of the animation pipeline. 
Your package works perfectly so far - just this strange detail that the output log tells the user constantly that there would be errors. And when I did use a cinematographic camera  instead of the default one, the generated picture always did disappear with the very last frame. 
Gratulations. Please announce, when we could hope for running tests of an animation pipeline. I include three trial runs, just for the pleasure.
![2022-10-12 19 42 10 (2)](https://user-images.githubusercontent.com/51109637/195420146-1904ebb8-2cda-4d1d-847f-9578b55c8272.png)
![2022-10-12 20 07 55 (2)](https://user-images.githubusercontent.com/51109637/195420149-a675198f-5196-4672-88bb-d0b45ea4ac68.png)
![2022-10-12 19 37 20 (2)](https://user-images.githubusercontent.com/51109637/195420151-1867151c-454a-4780-8b24-17acc45db89d.png)
[](url)

**Comment by Mystfit** [comment]
Those look great! You're officially the first person other than me to make something with the plugin. :D

The animation pipeline is coming along. I managed to get it working with the movie pipeline plugin last night to [output image sequences.](https://youtu.be/mvPSojfgGq8)

There's more work that has to be done in order to control the prompt parameters over time, but that's the next thing I will tackle.

**Comment by mischaschaub** [comment]
What a strange tool you created. Have been doing with sequencer a manual process, just stepping one frame and generating and saving etc for each pix. So I guess that the main problem is finding the ideal strength setting, so that it differs enough from the realistic UE5 image to be of interest. I attach the results of this first test.
![2022-10-13 09 03 01 (2)](https://user-images.githubusercontent.com/51109637/195530318-af4b5444-5759-4dae-b1b2-c499df3fb61e.png)

https://user-images.githubusercontent.com/51109637/195530367-b4c3d071-e1cf-47b4-b958-f79c83723f06.mp4
