### ISSUE TITLE
Fail to update in xformers

### ISSUE THREAD

**Issue by danke1** [Mystfit/Unreal-StableDiffusionTools#22]
![image](https://user-images.githubusercontent.com/79454653/210592759-c1a4904f-feee-4531-bb5d-207b16744607.png)

How can I handle with this?

I'm doing on UE5.1

**Comment by danke1** [comment]
I've resolved this by switching project to 5.1 source cord build!

**Comment by danke1** [comment]
![image](https://user-images.githubusercontent.com/79454653/210723991-0ab8a281-a34c-474d-aa5a-3e7defef7458.png)
 
this options is seperately with sequencer?

I need to upsample results from sequencer too..Is there upsampling option in sequencer too?

**Comment by Mystfit** [comment]
That's odd. It says that the wheel is invalid. Switching to a source code build shouldn't have fixed that issue so it may have just needed a redownload.
