### ISSUE TITLE
is Generate Image options seperate with sequencer track option?

### ISSUE THREAD

**Issue by danke1** [Mystfit/Unreal-StableDiffusionTools#23]
![image](https://user-images.githubusercontent.com/79454653/210724303-28354899-bdb8-45f8-bd06-abb769b448a2.png)

this options is seperate with sequencer?

I need to upsample results from sequencer too..Is there upsampling option in sequencer too?

**Comment by Mystfit** [comment]
![Screenshot 2023-01-06 124457](https://user-images.githubusercontent.com/795851/210901199-acb3be68-7367-4221-9add-861ab0d7ac79.png)

The SD Options track properties are separate from the main plugin window options. Here's where to make sure your sequencer output frames are upscaled after all the frames have finished rendering.
